apiVersion: batch/v1
kind: CronJob
metadata:
  name: aggregator-cronjob
spec:
  schedule: "0 0 * * 1" # Runs evry Monday at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: aggregator-service
              image: us-central1-docker.pkg.dev/moon-insurance/moon-insurance/aggregator-service:latest
              resources:
                requests:
                  cpu: "100m" # Reduce this value (100m = 0.1 CPU)
                  memory: "128Mi"
                limits:
                  cpu: "500m"
                  memory: "256Mi"
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: aggregator-service-db-secret
                      key: DATABASE_URL

                - name: REDSHIFT_URL
                  valueFrom:
                    secretKeyRef:
                      name: aggregator-service-redshift-secret
                      key: REDSHIFT_URL

                  volumeMounts:
                    - name: ssh-key
                      mountPath: "/root/.ssh"
                      readOnly: true

          volumes:
            - name: ssh-key
              secret:
                secretName: ssh-key
          restartPolicy: OnFailure
